spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: com.example.account.serializer.AccountSerializer

  consumer:
    bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.notification.service.deserializer.AccountCreationTopicDeserializer